# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-hello-word',
                'doc_host': 'https://luihzpg.github.io',
                'git_url': 'https://github.com/luihzpg/nbdev-hello-word',
                'lib_path': 'nbdev_hello_word'},
  'syms': {'nbdev_hello_word.core': {'nbdev_hello_word.core.foo': ('core.html#foo', 'nbdev_hello_word/core.py')}}}
